- name: Create a directory for the Flask app
  file:
    path: "{{ python_app_server_path }}"
    state: directory
    owner: ubuntu
    group: ubuntu

- name: Copy Flask app
  copy:
    src: "{{ python_app_local_file }}"
    dest: "{{ python_app_server_path }}"
    owner: ubuntu
    group: ubuntu
    mode: "0755"

- name: Copy Flask app systemd service
  template:
    src: "{{ systemd_python_app_service_template }}"
    dest: "{{ systemd_python_app_service_file }}"
  become: yes

- name: Reload systemd to apply new service
  systemd:
    daemon_reload: yes
  become: yes

- name: Enable and start Flask app service
  systemd:
    name: "{{ systemd_python_app_service_name }}"
    enabled: yes
    state: started
    daemon_reload: yes

- name: Restart Flask app service
  systemd:
    name: "{{ systemd_python_app_service_name }}"
    enabled: yes
    state: restarted
    daemon_reload: yes