- name: Update apt packages
  become: true
  apt:
    update_cache: yes

- name: Install apt packages
  apt:
    name: "{{ item }}"
    state: latest
  loop:
    - python3
    - python3-pip
    - nginx
    - e2fsprogs

- name: Install Python packages
  pip:
    name: flask
